config/routes.rb
UPCTwiter::Application.routes.draw do
  resources :tweets
  match "read_message" => "tweets#read_message"
  match "update_status" => "tweets#update_status"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :message, :url, :user

  Twitter.configure do |config|
    config.consumer_key = 'h18mqPUlfvgJe59qXu4Mw'
    config.consumer_secret = 'KbSdDaarKmPMROPdVBWHVrCfPoPUWYUBP6uwpLmZE'
    config.oauth_token = '71257300-8UtI4QdrmYCsI6CyfLLkXwz3VymemE4SU8g91tjOD'
    config.oauth_token_secret = 'BqGdU4aVyPwS8ajvL6DyagqegxzuBmdxztXYS9YxqE'
  end
  def read_message
    return "no hay user" if self.user.blank?
    Twitter.user_timeline(self.user).first.text
  end

  def update_status
  	return "no hay status" if self.message.blank?
  	Twitter.update(self.message)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json

  def read_message
     @tweet = Tweet.new(params[:tweet]);
     respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  def update_status
    @tweet = Tweet.new(params[:tweet]);
     respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end


  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UPCTwiter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/_formReadMessage.html.erb
<%= form_for(@tweet, :url => "read_message") do |f| %>
 
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit "Read Status"%>
  </div>
<% end %>

app/views/tweets/_formUpdateStatus.html.erb
<%= form_for(@tweet, :url => "update_status") do |f| %>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<%= render 'formReadMessage' %>

<%= render 'formUpdateStatus' %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/read_message.html.erb
<h2> Read Message</h2>
<%= @tweet.read_message %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @tweet.user %>
</p>

<p>
  <b>Message:</b>
  <%= @tweet.message %>
</p>

<p>
  <b>Url:</b>
  <%= @tweet.url %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/update_status.html.erb
<h2> Update Status</h2>
<% @tweet.update_status %>
<%= @tweet.message %>